aiven/go-client-codegen

client.go

Multi-error passes nil check, yet it is empty.

fix(logger): convert multierror to err

---

client_test.go
generator/main.go
generator/models.go
handler/account/account.go
handler/accountauthentication/accountauthentication.go
handler/billinggroup/billinggroup.go
handler/clickhouse/clickhouse.go
handler/domain/domain.go
handler/flinkapplication/flinkapplication.go
handler/flinkapplicationdeployment/flinkapplicationdeployment.go
handler/flinkjob/flinkjob.go
handler/kafka/kafka.go
handler/kafkaconnect/kafkaconnect.go
handler/kafkamirrormaker/kafkamirrormaker.go
handler/kafkaschemaregistry/kafkaschemaregistry.go
handler/kafkatopic/kafkatopic.go
handler/opensearch/opensearch.go
handler/organization/organization.go
handler/organizationuser/organizationuser.go
handler/privatelink/privatelink.go
handler/project/project.go
handler/projectbilling/projectbilling.go
handler/service/service.go
handler/serviceintegration/serviceintegration.go
handler/serviceuser/serviceuser.go
handler/staticip/staticip.go
handler/user/user.go
handler/vpc/vpc.go

Adds Out enum types to use them in comparisons, e.g.
```go
if s.Status == service.ServiceStateTypeRunning {
....
}
```

refactor: add out enum types

---

error.go

Replaces `OmitNotFound` with `IsNilOrNotFound` because `OmitNotFound` still requires additional `nil` check.

refactor: add IsNilOrNotFound, remove OmitNotFound

---

config.yaml
generator/models.go
handler/clickhouse/clickhouse.go

Adds `ServiceClickHouseQuery` and `ServiceClickHouseCurrentQueries` endpoints

feat: add new ClickHouse endpoints

---

generator/main.go
handler/kafkamirrormaker/kafkamirrormaker.go
handler/privatelink/privatelink.go
handler/service/service.go
handler/serviceuser/serviceuser.go

Multiline comments look weird on fields. 
Flattens the into a single line.

docs: flatten multiline comments

---

client.go
error.go
error_test.go
go.mod
go.sum

- Doesn't log _json_ response body, which might contain sensitive data
- Logs _non-json_ bodies
- Improves Error: `message` and `errors` fields takes values from [failed response](https://api.aiven.io/doc/#section/Responses/Failed-responses)
- Adds query params to logs
- Removes `IsNilOrNotFound` - useless

feat: improve errors

---

generator/main.go
handler/clickhouse/clickhouse.go
handler/service/service.go

Shared type allows to pass query params to other handlers that support them, but not expect.
Makes query types private.

feat: make private query param types

---

.golangci.yaml
generator/main.go
generator/models.go

Fixes deprecated golangci-lint linters and options
No more deprecation warnings

feat: fix linter deprecation warnings

---

config.yaml
handler/kafkaschemaregistry/kafkaschemaregistry.go
handler/kafkatopic/kafkatopic.go
handler/project/project.go
handler/service/service.go
handler/serviceuser/serviceuser.go

Add service plan APIs to generated client.
* https://api.aiven.io/doc/#tag/Project/operation/ProjectServicePlanList
* https://api.aiven.io/doc/#tag/Project/operation/ProjectServicePlanPriceGet
* https://api.aiven.io/doc/#tag/Project/operation/ProjectServicePlanSpecsGet
* https://api.aiven.io/doc/#tag/Project/operation/ProjectServiceTypesGet
* https://api.aiven.io/doc/#tag/Project/operation/ProjectServiceTypesList
Makes it possible to address the following fixme comments:
* https://github.com/aiven/terraform-provider-aiven/blob/a76a6b5aff9627df49b100c61c48be9e3551a4b9/internal/schemautil/helpers.go#L95
* https://github.com/aiven/terraform-provider-aiven/blob/a76a6b5aff9627df49b100c61c48be9e3551a4b9/internal/schemautil/helpers.go#L108
... as well as migrate go-api-schemas to fetch service …

feat: add service plan APIs

---

client.go

Modify retryablehttp retry setting values:
* RetryWaitMin: increase to 2 seconds (library default is 1 second)
* RetryWaitMax: decrease to 10 seconds (library default is 30 seconds)
* RetryMax: increase to 6 (library default is 4)
Explanation of chosen values:
| Run | Default Values (retryWaitMin = 1s, retryWaitMax = 30s, retryMax = 4) | Changed Values (retryWaitMin = 2s, retryWaitMax = 10s, retryMax = 6) |
|-----|----------------------------------------------------------------------|---------------------------------------------------------------------|
| 0   | 0.000                                                                | 0.000                                                               |
| 1   | 1.000                                                                | 2.000 …

feat: modify retryablehttp retry setting values

---

client.go

feat: tweak client retry settings

---

.github/workflows/update.yml

Close previous PRs created by this workflow when a new one is created. Example [run](https://github.com/aiven/go-client-codegen/actions/runs/11028894847/job/30630083426):
```
Run new_pr_number=148
✓ Closed pull request aiven/go-client-codegen#147 (chore(update): bump openapi schema (2024-09-25))
! Skipped deleting the local branch since current directory is not a git repository 
✓ Deleted branch update/2024-09-25
```
Comment is added to the previous PR referencing the new PR: https://github.com/aiven/go-client-codegen/pull/147#issuecomment-2373361346
PR list before:
PR list after:
The action is ran every day on a cron schedule, and if the update from yesterday wasn't merged, we'd have two PRs open. The previous one would have to be closed manually.

feat: close previous update PRs when a new one is generated

---

config.yaml
generator/config_check.go
generator/main.go

Adds a custom trunk check that detects duplicate endpoints in config.yaml.
The check looks like this:
```bash
❯ task generate
task: [get-openapi-spec] curl -s -o openapi.json https://api.aiven.io/doc/openapi.json
task: [go-generate] rm -rf handler
task: [go-generate] GEN_OUT_DIR=handler go run -tags=generator ./generator/...
2024-10-04T15:45:13+03:00 ERR error="Duplicate endpoints found in config: [AccountUsersSearch]"
task: [fmt-imports] find . -type f -name '*.go' -exec sed -zi 's/(?<== `\s+)"\n\+\t"/"\n"/g' {} +
task: [fmt-imports] goimports -local "github.com/aiven/go-client-codegen" -w .
```
Cleaner config

feat: add check to detect duplicate endpoints in config.yaml

---

client_test.go
generator/main.go
generator/models.go
handler/account/account.go
handler/accountauthentication/accountauthentication.go
handler/accountteam/accountteam.go
handler/clickhouse/clickhouse.go
handler/project/project.go
handler/service/service.go
handler/user/user.go

Adds `customCamelCase` helper to improve naming. For example `MemberTypeProjectpermissionsread` is renamed to `MemberTypeProjectIntegrationsRead`

feat: improve variable and type naming

---

.github/workflows/update.yml

Same as https://github.com/aiven/go-api-schemas/pull/220
See: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-outputs

fix: attempt to close previous PRs only if a new one was created

---

client.go
client_test.go
error.go
error_test.go
option.go

Uses retryablehttp.PassthroughErrorHandler to return response body as an error. By default retryablehttp returns attempts information instead.

fix: return response body on error status code

---

config.yaml
handler/kafka/kafka.go
handler/service/service.go

generate handlers for kafka native acl endpoints.
Adds support for managing kafka native acls
So one can manage kafka native acls through client

feat: add kafka native acl

---

Taskfile.yml
client_test.go
config.yaml
generator/config_check.go
generator/main.go
handler/account/account.go
handler/billinggroup/billinggroup.go
handler/kafka/kafka.go
handler/project/project.go
handler/user/user.go

fix: detect unknown operation ids

---

generator/main.go

Stringifies non-string values and enums

fix: do not stringify string query params

---

client_test.go
error.go
error_test.go

Usually we get errors like this, and the message is just duplicated:
```
Error: error creating a service: [400 ServiceCreate]: Service 'foo' version '1.8' has reached end of availability and cannot be created: [{"message":"Service 'foo' version '1.8' has reached end of availability and cannot be created","status":400}]
```

feat: do not duplicate error message

---

generator/main.go
handler/clickhouse/clickhouse.go
handler/kafka/kafka.go
handler/service/service.go

Allows to use custom query params.

feat: allow custom query params

---

client.go
client_test.go
handler/kafka/kafka.go
openapi_patch.yaml

- patched ServiceKafkaQuotaDescribe parameters. 
- limited the "limit" query param that added to the queries.

fix: patched ServiceKafkaQuotaDescribe parameters
