.github/workflows/lint.yml

fixes `trunk`'s failing annotations write attempt
to make it work

ci(trunk): fix failing annotations write attempt

---

config.yaml
handler/project/project.go

feat: add ProjectKmsGetCA

---

.github/workflows/release.yml
.github/workflows/update.yml
client.go
client_test.go
generator/main.go

- adds auto update and release workflow, similar to the approach in other Go projects, such as `go-api-schemas` and `aiven-go-client`
- fixes lint problems 
to make life easier

ci: auto update and release

---

.github/workflows/release.yml
client.go
version.go

Adds a fixed `User-Agent` for telemetry purposes.
To get the data collected and analyzed, in order to be able to further improve and refine the client.

feat(client): user-agent telemetry

---

client.go
client_test.go

refactor: cache user agent

---

.github/workflows/update.yml

- Fixes the cron job
- Allows manual dispatch

fix: cron job fails with goimports dependency

---

generator/models.go
handler/kafkamirrormaker/kafkamirrormaker.go

fix: topics.blacklist

---

config.yaml
generator/main.go
generator/models.go
handler/account/account.go
handler/accountteam/accountteam.go
handler/accountteammember/accountteammember.go
handler/billinggroup/billinggroup.go
handler/kafkaschemaregistry/kafkaschemaregistry.go
handler/user/user.go

Generates deprecated endpoints.

fix: generate deprecated endpoints

---

config.yaml
handler/organization/organization.go

feat: add user permissions

---

generator/main.go
handler/kafkatopic/kafkatopic.go

Handles all cases with non-word characters.

refactor: improve customCamelCase

---

generator/main.go
handler/account/account.go
handler/accountteam/accountteam.go
handler/applicationuser/applicationuser.go
handler/billinggroup/billinggroup.go
handler/kafkamirrormaker/kafkamirrormaker.go
handler/organizationuser/organizationuser.go
handler/project/project.go
handler/service/service.go
handler/user/user.go
handler/vpc/vpc.go

feat: unescape html entities

---

handler/service/service.go
openapi_patch.yaml

Add lc_ctype and lc_collate, which are missing from the OpenAPI spec.

feat: patch ServiceDatabaseListResponse

---

config.yaml
handler/service/service.go

feat: add AlloyDB Omni key APIs

---

handler/account/account.go
handler/billinggroup/billinggroup.go
handler/kafka/kafka.go
handler/project/project.go
handler/user/user.go

This reverts commit 568c4bda51384d2127ae8899ea45766f9bafd70d.

Revert "chore(update): bump openapi schema (2024-12-10)"

---

.gitignore
Taskfile.yml
handler/kafka/kafka.go
openapi_patch.yaml

- mark ServiceKafkaQuotaDescribe parameters as optional

fix: patched ServiceKafkaQuotaDescribe required parameters

---

client_test.go
generator/main.go
handler/clickhouse/clickhouse.go
handler/kafka/kafka.go
handler/service/service.go

A single query param was never included.

fix: single query param not included

---

generator/main.go
generator/models.go
handler/service/service.go
openapi_patch.yaml

- Adds nullable fields support
- Marks VPC id nullable

feat: mark project vpc id nullable

---

generator/models.go
handler/account/account.go
handler/accountauthentication/accountauthentication.go
handler/accountteam/accountteam.go
handler/billinggroup/billinggroup.go
handler/clickhouse/clickhouse.go
handler/flinkapplication/flinkapplication.go
handler/flinkapplicationdeployment/flinkapplicationdeployment.go
handler/flinkjarapplication/flinkjarapplication.go
handler/flinkjarapplicationdeployment/flinkjarapplicationdeployment.go
handler/flinkjarapplicationversion/flinkjarapplicationversion.go
handler/flinkjob/flinkjob.go
handler/kafkaconnect/kafkaconnect.go
handler/kafkatopic/kafkatopic.go
handler/opensearch/opensearch.go
handler/organization/organization.go
handler/postgresql/postgresql.go
handler/privatelink/privatelink.go
handler/projectbilling/projectbilling.go
handler/service/service.go
handler/staticip/staticip.go
handler/user/user.go

Sorts enum values to minimize diffs during schema changes.

refactor: sort enum values for consistency

---

config.yaml
handler/user/user.go

- added UserCreditCardsList operation

feat(cards): added UserCreditCardsList operation

---

config.yaml
handler/organization/organization.go

Adds `OrganizationAddress` handlers

feat: add OrganizationAddress handlers

---

config.yaml
handler/organization/organization.go

feat: add `PermissionsSet` API

---

.trunk/trunk.yaml
go.mod

- upgraded `go` to version `1.24`

chore(go): upgraded go version

---

config.yaml
handler/organizationprojects/organizationprojects.go

feat: add OrganizationProjectsGet

---

generator/main.go
handler/organizationprojects/organizationprojects.go
handler/project/project.go
handler/service/service.go

Improves deprecation warnings.

refactor: use conventional deprecation identifier

---

generator/models.go
handler/clickhouse/clickhouse.go
openapi_patch.yaml

Resolves NEX-99.
Generates a pointer for required & nullable fields.

fix: ClickHouseUser password is nullable

---

generator/main.go

fix: exit code 1 on generation error

---

config.yaml
generator/models.go
handler/kafkatopic/kafkatopic.go
handler/project/project.go
handler/service/service.go
openapi_patch.yaml

Resolves NEX-1845.
- Fixes camel case issues for strings with digits
- Adds `ServiceKafkaTopicListV2` endpoint through the patching

feat: `ServiceKafkaTopicListV2` endpoint
